// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXswhgsMT4ugb54C2kWDw8o2jAqTNbluo',
    appId: '1:486459863712:web:0e8f5aab5b1963c821cfc5',
    messagingSenderId: '486459863712',
    projectId: 'learnapp-bd021',
    authDomain: 'learnapp-bd021.firebaseapp.com',
    storageBucket: 'learnapp-bd021.firebasestorage.app',
    measurementId: 'G-YJ8L5JEM8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbeGkj_7lvfj0R_oN7mMyzKluly-dqzBo',
    appId: '1:486459863712:android:bdb7d475120ea3d321cfc5',
    messagingSenderId: '486459863712',
    projectId: 'learnapp-bd021',
    storageBucket: 'learnapp-bd021.firebasestorage.app',
  );
}
